### PR TITLE
115-add-error-handling (resolves #115)

### LINKED ISSUE #115: Add Error Handling and Styled Messages
### Description
Add error messages for authentication pages
- Login
- Create account

The login page/create account has a couple different errors, the task is to "catch" each error and display the appropriate error. Some may include: email already exists, password incorrect, password too short, empty field error, etc. You can also check the documentation for the error types, if necessary.

### Success Metrics Checklist
- [ ] Login errors handled (best of your ability)
- [ ] Create account errors handled (best of your ability)

Finally, on your pull request, please request a code review from me (@ObjectJosh)

### PR DESCRIPTION
**Pull request by Xeygy**
<p float="left" align="middle">
Screen Shot 2022-08-06 at 11 29 25 AM
Screen Shot 2022-08-06 at 11 29 35 AM
</p>

- Errors now handled through the screen instead of alert() on login and create account pages.
- AWS errors are being displayed using error.message, i.e. "Password did not conform with policy: Password not long enough." 
- Frontend checks are limited to the most basic ones so far (not empty, has @, only numbers, etc.)

### CODE REVIEW

File: frontend/src/components/authentication/CreateAccountPage/CreateAccountPage.tsx [hunk 1]
```diff
@@ -118,112 +128,147 @@ const CreateAccountPage = (): JSX.Element => {
...
-            alert("Please add email");
+            setEmailError("Please enter your email");
             return false;
         }
         else if (!email.includes("@")) {
-            alert("Please enter a valid email address");
+            setEmailError("Please enter a valid email address");
             return false;
         }
         //else if (check if email already exists)
```
Comment (ObjectJosh) [inline frontend/src/components/authentication/CreateAccountPage/CreateAccountPage.tsx:222]: I would use a package with an isEmail() function that validates the email regex more thoroughly: [https://www.npmjs.com/package/validator](url)
Usage:
```js
import isEmail from 'validator/lib/isEmail';
...
if (email === '' || !isEmail(email)){
// set error
...
```

File: frontend/src/components/authentication/CreateAccountPage/CreateAccountPage.tsx [hunk 2]
```diff
@@ -118,112 +128,147 @@ const CreateAccountPage = (): JSX.Element => {
...
         //alert("Account with this email already exists")
```
Comment (ObjectJosh) [inline frontend/src/components/authentication/CreateAccountPage/CreateAccountPage.tsx:223]: From manually checking, this error works so you may delete the comment
Screen Shot 2022-08-09 at 10 34 09 AM

```suggestion
```

File: frontend/src/components/authentication/CreateAccountPage/CreateAccountPage.tsx [hunk 3]
```diff
@@ -118,112 +128,147 @@ const CreateAccountPage = (): JSX.Element => {
...
-            alert(`Please choose a password at least ${MIN_PASSWORD_LENGTH} characters long`);
+            setPasswordError(`Please choose a password at least ${MIN_PASSWORD_LENGTH} characters long`);
             return false;
         }
+        setPasswordError("");
         return true;
     }
 
-    function processPhoneNumber(): boolean {
+    function processPhoneNumber(phoneNumber: string): boolean {
```
Comment (ObjectJosh) [inline frontend/src/components/authentication/CreateAccountPage/CreateAccountPage.tsx:246]: Please check how thorough this function is. I would also add in another function from the validator package mentioned above:
using the `isMobilePhone(str [, locale [, options]])` function

File: frontend/src/components/authentication/CreateAccountPage/CreateAccountPage.tsx [hunk 4]
```diff
@@ -118,112 +128,147 @@ const CreateAccountPage = (): JSX.Element => {
...
             return false;
         }
         //else if (check if email already exists)
         //alert("Account with this email already exists") 
+        setEmailError("");
         return true;
     }
 
-    const validatePassword = (): boolean => {
+    const validatePassword = (password: { value: string; }): boolean => {
```
Comment (ObjectJosh) [inline frontend/src/components/authentication/CreateAccountPage/CreateAccountPage.tsx:228]: In the validator package, this function could be something cool to play around with: `isStrongPassword(str [, options])`. If you want, you can have a live text that shows how strong the password is, since the function can return an integer "strength" with `returnScore`. Optional task.

File: frontend/src/components/authentication/CreateAccountPage/CreateAccountPage.tsx [hunk 5]
```diff
@@ -77,10 +85,12 @@ const CreateAccountPage = (): JSX.Element => {
         }).catch(
             error => {
                 const code = error.code;
+                debugger;
                 console.log(error);
+                setPasswordError(error.message);
                 switch (code) {
                     case 'UsernameExistsException':
-                        alert("Account already exists");
+                        //alert("Account already exists");
```
Comment (ObjectJosh) [inline frontend/src/components/authentication/CreateAccountPage/CreateAccountPage.tsx:93]:
```suggestion
```

File: frontend/src/components/authentication/CreateAccountPage/CreateAccountPage.tsx [hunk 6]
```diff
@@ -77,10 +85,12 @@ const CreateAccountPage = (): JSX.Element => {
         }).catch(
             error => {
                 const code = error.code;
+                debugger;
                 console.log(error);
+                setPasswordError(error.message);
                 switch (code) {
                     case 'UsernameExistsException':
```
Comment (ObjectJosh) [inline frontend/src/components/authentication/CreateAccountPage/CreateAccountPage.tsx:92]: This is good that you're setting the message to the `error.message` just please clean up debugger lines and console logs
```suggestion
                setPasswordError(error.message);
                switch (code) {
                    case 'UsernameExistsException':
```

For more info on AWS signUp errors, you can check out this link if you haven't already [https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SignUp.html#errors:~:text=Type%3A%20String-,Errors,-For%20information%20about](url)

Comment (ObjectJosh) [reply frontend/src/components/authentication/CreateAccountPage/CreateAccountPage.tsx:92]: The switch statement might be pointless, since all errors should stop it anyway. Check and make sure I'm if I'm correct or not tho

**Comment by ObjectJosh** [comment]
Feedback
- [ ] Doesn't error when first name is filled but not last name
- [ ] Make sure for name they can't put only spaces (don't strip spaces, but just make sure it not only spaces)
- [ ] So when a user creates an account they still need to verify their account. I tried to login with an account that hasn't been verified yet and it brought me to a white screen because it errored out (check console). This one's a tricky one so ask me if you have any questions. To handle this error, I would probably direct them to a verify email screen and send them a new one.

**Review by ObjectJosh — CHANGES_REQUESTED** [review]

**Comment by ObjectJosh** [comment]
Screen Shot 2022-08-09 at 11 04 39 AM

Reference for what the create account page should look like

File: frontend/src/components/authentication/CreateAccountPage/CreateAccountPage.tsx (hunk 3 above)
Comment (Xeygy) [reply frontend/src/components/authentication/CreateAccountPage/CreateAccountPage.tsx:241]: With isMobilePhone I set it to only accept US formatted numbers (e.g. (XXX)-XXX-XXXX or 1-(XXX)-XXX-XXXX).

Comment (ObjectJosh) [reply frontend/src/components/authentication/CreateAccountPage/CreateAccountPage.tsx:241]: Yes, that should be fine

**Comment by Xeygy** [comment]
I've applied suggested changes to name, email & phone number verification, formatting works on 800px height screens and the redirect happens now.

**Review by ObjectJosh — APPROVED** [review]
Looks great!
